### ISSUE TITLE
感谢老哥大吉大利，求您的模块适配4.54.0版的soul

### ISSUE THREAD

**Issue by shajia1992** [ChengmingFan/LuoS#1]
感谢老哥大吉大利，求您的模块适配4.54.0版的soul

**Comment by ChengmingFan** [comment]
目前工作主要在4.67.0上 如果可以的话 使用这个版本最好。

**Comment by ChengmingFan** [comment]
之后有时间的话 可以适配一下

**Comment by BaileyZyp** [comment]
> 目前工作主要在4.67.0上 如果可以的话 使用这个版本最好。

ColorOS 13系统打开此模块会闪退
