### ISSUE TITLE
ColorOS 13系统打开会闪退

### ISSUE THREAD

**Issue by BaileyZyp** [ChengmingFan/LuoS#2]
![Screenshot_2023-03-11-01-57-47-87_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/16634459/224389658-b8a92d06-d2b6-437d-872f-598ac1c9e425.jpg)
安装的是最新版本

**Comment by ChengmingFan** [comment]
在LSPosed中激活了吗

**Comment by BaileyZyp** [comment]
> 在LSPosed中激活了吗

肯定激活了呀，而且就算没激活也不应该闪退吧

**Comment by ChengmingFan** [comment]
开发使用的是原生安卓 不了解ColorOS

**Comment by ChengmingFan** [comment]
> > 在LSPosed中激活了吗
> 
> 肯定激活了呀，而且就算没激活也不应该闪退吧

我更新了1.1.1 重新下载安装一下 如果还是不行那就是用不了了

**Comment by BaileyZyp** [comment]
> > > 在LSPosed中激活了吗
> > 
> > 
> > 肯定激活了呀，而且就算没激活也不应该闪退吧
> 
> 我更新了1.1.1 重新下载安装一下 如果还是不行那就是用不了了

OK 等下我空了试一下

**Comment by BaileyZyp** [comment]
OK了 不闪退了
